// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import MainMenuController from "./main_menu_controller"
application.register("main-menu", MainMenuController)

import TurboModalController from "./turbo_modal_controller"
application.register("turbo-modal", TurboModalController)
